<a href="https://colab.research.google.com/github/carlasolrocca/api-movies/blob/master/unidad_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Álgebra lineal

Aunque algunos pueden confundir el **álgebra lineal** con el **álgebra básica**, en realidad es mucho más abstracta, centrada en `vectores` y `matrices`.  

Se ocupa de sistemas lineales representados a través de espacios vectoriales y matrices.  

Si no estás familiarizado con estos conceptos, no hay problema; los vamos a explorar detalladamente.  

El álgebra lineal es fundamental en varias áreas aplicadas como estadísticas, investigación operativa, ciencia de datos y aprendizaje automático.  

Cuando trabajas con datos en estas áreas, estás utilizando álgebra lineal, muchas veces sin darte cuenta.  

Es posible evitar el aprendizaje profundo del álgebra lineal por un tiempo, gracias a las bibliotecas de aprendizaje automático y estadísticas que automatizan estos procesos. Sin embargo, para realmente comprender lo que sucede detrás de las escenas y trabajar de manera más efectiva con los datos, es inevitable entender los fundamentos del álgebra lineal.  

Aunque es un tema extenso que no podemos abarcar completamente en una sola clase, podemos aprender lo suficiente para sentirnos más cómodos con él y movernos de manera efectiva en el ámbito de la ciencia de datos. Además, habrá oportunidades de aplicar estos conceptos en capítulos posteriores.

### ¿Qué es un vector?

Según los físicos, un vector es una flecha en el espacio con una dirección y longitud específicas, que suele representar datos, por ejemplo, velocidad y dirección.  

Para un programador, un vector es una lista ordenadas de números que se pueden sumar entre sí, y la dimensión del vector es qué cantidad de elementos tiene esa lista.  

Para un matemático, un vector es un conjunto de cosas que se pueden **sumar entre ellos y multiplicar por un número**.

En criollo, es una flecha que tiene principio, fin, dirección, largo y sentido.  

Es el pilar central del álgebra lineal, incluyendo matrices y transformaciones lineales.  

En su forma más fundamental, no tiene un concepto de ubicación, así que siempre imagina que su cola comienza en el origen de un plano cartesiano (0,0).

La figura que sigue muestra un vector que avanza tres pasos en dirección horizontal y dos pasos en la vertical.  

![vector.png](attachment:image.png)

El propósito del vector es representar visualmente un pedazo de datos.  

Si tenemos un registro de datos para los metros cuadrados de una casa de 1.672 metros cuadrados y su valoración de $260.000, podríamos expresar eso como un vector [1672, 260000], avanzando 1.672 pasos en dirección horizontal y 260.000 pasos en la dirección vertical.  

Declaramos un vector matemáticamente así:

$$\overrightarrow{v}={x\brack y}$$

Poniendo valores:

$$\overrightarrow{v}={3\brack 2}$$


Podemos declarar un vector usando una colección simple de Python, como una lista común y corriente, o como vimos en la clase anterior: utilizando `numpy`.

<div class="alert alert-block alert-info">
<b>Nota:</b> Cuando comenzamos a realizar cálculos matemáticos con vectores, especialmente al realizar tareas como el aprendizaje automático, probablemente deberíamos usar la biblioteca `NumPy`, ya que es más eficiente que las listas de Python nativas.
</div>

In [ ]:
v = [3, 2]
print(v)

[3, 2]


In [ ]:
import numpy as np
v = np.array([3, 2])
print(v)
print(v.shape)

[3 2]
(2,)


<div class="alert alert-block alert-danger">
<b>Importante:</b> Python es lento en términos computacionales, ya que no se compila a código de máquina de bajo nivel o bytecode como Java, C#, C, etc.  
Se interpreta de manera dinámica en tiempo de ejecución.  
Sin embargo, las bibliotecas numéricas y científicas de Python no son lentas.  
</div>  


Bibliotecas como NumPy están escritas en lenguajes de bajo nivel como C y C++, por eso son computacionalmente eficientes.  

Python realmente actúa como un "código pegamento" integrando estas bibliotecas para tus tareas.

## Dimensiones  

El vector "v" que declaramos recién, es de 2 dimensiones, y es difícil imaginarse un vector de más de 3 dimensiones. Pero en realidad, nos alcanza con saber que podemos generalizar y podemos tener vectores de tantas dimensiones como queramos:
$$\overrightarrow{v}= \left(\begin{matrix} 3 \\ 2 \\ 18 \\ 2 \\ 9
\end{matrix}\right)$$


In [ ]:
v = np.array([3, 2, 18, 2, 9])
print(v)
print(v.shape)

[ 3  2 18  2  9]
(5,)



## Sumar Vectores
Efectivamente combinamos los movimientos de dos vectores en un solo vector.

Digamos que tenemos dos vectores: $$\overrightarrow{v} ; \overrightarrow{w}$$

¿Cómo los sumamos?

![vectores_v_y_W.png](attachment:image.png)

Numéricamente es bastante sencillo: sumamos los valores del eje *x* y eso nos va a dar la resultante en *x*, y hacemos lo mismo para el eje *y*.

$$\overrightarrow{v} + \overrightarrow{w} = \left(\begin{matrix} 3 \\ 2 \end{matrix}\right) + \left(\begin{matrix} 2 \\ -1 \end{matrix}\right)$$

$$\overrightarrow{v} + \overrightarrow{w} = \left(\begin{matrix} 3 + 2 \\ 2 + (-1) \end{matrix}\right) $$

$$\overrightarrow{v} + \overrightarrow{w} = \left(\begin{matrix} 5 \\ 1 \end{matrix}\right) $$


In [ ]:
from numpy import array

v = array([3,2])
w = array([2,-1])

# sum the vectors
v_plus_w = v + w

# display summed vector
print(v_plus_w)

[5 1]


Visualmente, esto es como correr la base del vector a sumar donde termina el vector anterior:  
![image.png](attachment:image.png)

Y veamos que es lo mismo cuál de los dos sumo primero, es decir, la adición de vectores es conmutativa:  
![image.png](attachment:image.png)

## Escalando Vectores
Escalar es aumentar o disminuir la longitud de un vector. Se puede hace crecer/reducir un vector multiplicándolo o escalándolo con un valor único, conocido como escalar.  

![image.png](attachment:image.png)  

Matemáticamente, esto es multiplicar cada una de las dimensiones por el escalar.  


$$\overrightarrow{v} = \left(\begin{matrix} 3 \\ 1 \end{matrix}\right) $$
$$ 2 \overrightarrow{v} = 2 \left(\begin{matrix} 3 \\ 1 \end{matrix}\right) = \left(\begin{matrix} 2 \times 3 \\  2 \times 1 \end{matrix}\right) = \left(\begin{matrix} 6 \\  2 \end{matrix}\right) $$

In [ ]:
v = array([3,1])

# scale the vector
scaled_v = 2.0 * v

# display scaled vector
print(scaled_v)

[6. 2.]


#### Manipular datos es manipular vectores
Cada operación con datos puede pensarse en términos de vectores, incluso promedios simples.

Tomemos el escalado, por ejemplo.  

Digamos que intentábamos obtener el valor promedio de una casa y el metraje cuadrado promedio para todo un vecindario.  

Sumaríamos los vectores juntos para combinar su valor y metraje cuadrado respectivamente, dándonos un vector gigante que contiene tanto el valor total como el metraje cuadrado total.  

Luego, escalamos hacia abajo el vector dividiéndolo por el número de casas *N*, que realmente es multiplicar por *1/N*. Ahora tenemos un vector que contiene el valor promedio de la casa y el metraje cuadrado promedio.

<div class="alert alert-block alert-info">
<b>Nota:</b> Escalar un vector no le cambia la dirección, solamente lo estira o lo contrae. Lo importante de notar es que si el escalar es negativo, no cambia la dirección pero sí el sentido.
</div>

![image.png](attachment:image.png)

#### Extensión y Dependencia Lineal
Estas dos operaciones, sumar dos vectores y escalarlos, dan lugar a una idea simple pero poderosa:  
- Con estas dos operaciones, podemos combinar dos vectores y escalarlos para crear cualquier vector resultante que queramos.

En la imagen vemos 6 ejemplos de tomar dos vectores, escalarlos y sumarlos.  

Estos vectores:
$$\overrightarrow{v} ; \overrightarrow{w} $$

Tienen cada uno su dirección y sentido fijos, pero pueden ser escalados y combinados para crear **cualquier** otro vector nuevo.  

![image.png](attachment:image.png)


De nuevo, estos vectores tienen direcciones fijas, excepto por el cambio con escalares negativos, pero podemos usar el escalado para crear libremente cualquier vector compuesto por estos dos originales.

Todo este espacio de vectores posibles se llama extensión, y en la mayoría de los casos nuestra extensión puede crear vectores ilimitados a partir de esos dos vectores, simplemente escalándolos y sumándolos.  

<div class="alert alert-block alert-warning">
<b>Pregunta:</b> ¿en qué caso estamos limitados en los vectores que podemos crear?
</div>

---

Cuando tenemos dos vectores en dos direcciones diferentes, son linealmente independientes y tienen esta extensión ilimitada.

¿Qué pasa cuando dos vectores existen en la misma dirección o existen en la misma línea?  

La combinación de esos vectores también está limitada a la misma línea, limitando nuestra extensión a solo esa línea. No importa cómo lo escales, el vector suma resultante también está limitado a esa misma línea. Esto los hace **linealmente dependientes**.  

![image.png](attachment:image.png)

¿Y cómo podría encontrarme con este mismo problema en más dimensiones?  

![image.png](attachment:image.png)  

Por ejemplo, si tengo 3 o más dimensiones, capaz que son linealmente dependientes entre sí y quedo limitado.  

<div class="alert alert-block alert-info">
<b>Nota:</b> Más adelante vamos a revisar el concepto de determinante que nos ayuda con este problema.
</div>

¿Pero por qué nos importa si dos vectores son linealmente dependientes o independientes?  

Muchos problemas se vuelven difíciles o irresolubles cuando son linealmente dependientes. Por ejemplo, cuando aprendamos sobre sistemas de ecuaciones más adelante en este capítulo, un conjunto de ecuaciones linealmente dependiente puede hacer que las variables desaparezcan y volver el problema irresoluble.  

¡Pero si tenemos independencia lineal, esa flexibilidad para crear cualquier vector que necesites a partir de dos o más vectores se vuelve invaluable para encontrar una solución!

## Transformaciones lineales

Este concepto de sumar dos vectores con dirección fija, pero escalarlos para tener distintos resultados de las sumas, es bastante importante.  

Este vector resultante, exceptuando los casos de dependencia lineal, nos puede apuntar en cualquier dirección, y puede tener el largo que nosotros queramos.  

Esto prepara la intuición para transformaciones lineales, donde usamos vectores para llegar a otros, de un estilo de "funciones".

### Vectores Base

Los vectores conocidos como vectores base, se utilizan para describir transformaciones en otros vectores. Típicamente tienen una longitud de 1 y apuntan en direcciones positivas perpendiculares.

Piensa en los vectores base como bloques de construcción para construir o transformar cualquier vector.


![image.png](attachment:image.png)

Nuestro vector base se expresa en una matriz de 2x2, donde la primera columna es *i* y la segunda *j*

$$\overrightarrow{i} = \dbinom{1}{0} $$
$$\overrightarrow{j} = \dbinom{0}{1} $$

$$ base = \begin{pmatrix}
   1 & 0 \\
   0 & 1
\end{pmatrix} $$

Una matriz es una colección de vectores (como *î* y *^j*) que puede tener múltiples filas y columnas, y es una forma conveniente de empaquetar datos. Podemos usar *i* y *j*  para crear cualquier vector que deseemos escalándolos y sumándolos.

Comencemos con el vector
$$\overrightarrow{v} = \dbinom{1}{1} $$

¿Cómo logramos que el vector *v* apunte al [3, 2]?
Veamos qué sucede si multiplicamos a *î* por un factor de 3 y a *j* por un factor de 2 y luego los sumamos
$$ 3 \overrightarrow{i} = 3 \dbinom{1}{0} = \dbinom{3}{0} $$
$$ 2 \overrightarrow{j} = 2 \dbinom{0}{1} = \dbinom{0}{2} $$
$$ \overrightarrow{v} = \dbinom{3}{0} + \dbinom{0}{2} = \dbinom{3}{2} $$

![image.png](attachment:image.png)


 Esto se conoce como una **transformación lineal**, donde modificamos un vector mediante estiramiento, compresión, inclinación o rotación, siguiendo los movimientos de los vectores base. En resumen, al escalar los vectores *î* y *j*, también estiramos el espacio en el que se encuentra el vector *v*

Generalmente, en transformaciones lineales hay cuatro movimientos que se pueden hacer: escalar, rotar, inclinar

![image.png](attachment:image.png)

Estas cuatro transformaciones lineales son una parte central del álgebra lineal. Escalar un vector lo estirará o lo comprimirá. Las rotaciones girarán el espacio vectorial, y las inversiones darán la vuelta al espacio vectorial para que *î* y *j* intercambien sus lugares respectivos.

<div class="alert alert-block alert-info">
<b>Importante:</b> no puedes tener transformaciones que sean no lineales, lo que resultaría en transformaciones curvas o sinuosas que ya no respetan una línea recta. ¡Por eso lo llamamos álgebra lineal, no álgebra no lineal!
</div>

### Multiplicación de matrix por vector

La multiplicación de una matriz por un vector nos permite seguir la trayectoria de dónde terminan los vectores *î* y *j* después de una transformación. Esto es crucial porque no solo nos permite crear nuevos vectores, sino también transformar los vectores existentes.

La fórmula para transformar un vector *v* dado los vectores base empaquetados como una matriz es la siguiente:
$$ \dbinom{x_{nuevo}}{y_{nuevo}} = \begin{pmatrix} a & b \\ c & d\end{pmatrix} \dbinom{x}{y}$$
$$ \dbinom{x_{nuevo}}{y_{nuevo}} = \begin{pmatrix} ax + by \\ cx + dy\end{pmatrix}$$

Esta transformación de un vector aplicando vectores base se conoce como multiplicación de matriz por vector. En resumen, esta fórmula es una manera eficiente de escalar y sumar los vectores base *î* y *j*, tal como lo hicimos anteriormente, y luego aplicar esa transformación a cualquier vector *v*.

Para ejecutar esta transformación en Python utilizando NumPy, necesitaremos declarar nuestros vectores base como una matriz y luego aplicarla al vector *v* usando el operador **dot()**. El operador dot() realizará esta escala y adición entre nuestra matriz y el vector como acabamos de describir. Esto se conoce como el producto punto.

In [ ]:
from numpy import array

# matriz base compuesta por vectores i y j
basis = array(
    [[3, 0],
     [0, 2]]
 )

# declaro vector v
v = array([1,1])

# creo un nuevo vector transformando v con el producto punto
new_v = basis.dot(v)

print(new_v)

[3 2]


Cuando se piensa en términos de vectores base, es preferible separar los vectores base y luego componerlos en una matriz. Solo hay que tener en cuenta que se necesitará transponer, o intercambiar las filas y columnas. Esto se debe a que la función array() de NumPy realizará la orientación opuesta a la que queremos, poblándola con cada vector como una fila en lugar de una columna.

In [ ]:
from numpy import array

# Declaro los vectores
i_hat = array([2, 0])
j_hat = array([0, 3])

# Compongo la matriz base con los vectores
# necesito trasponer filas en columnas
basis = array([i_hat, j_hat]).transpose()

# Declaro vector v
v = array([1,1])

# Creo nuevo vector
# transformando v con el producto punto
new_v = basis.dot(v)

print(new_v)

[2 3]


Veamos otro ejemplo: comencemos con el vector *v* = [2,1] y los vectores *î* = [1, 0] y *j* = [0, 1]. Si transformamos los vectores *î* y *j* a [2, 0] y [0, 3] respectivamente, qué pasaría con el vector *v*?

$$ \dbinom{x_{nuevo}}{y_{nuevo}} = \begin{pmatrix} a & b \\ c & d\end{pmatrix} \dbinom{x}{y} = \begin{pmatrix} ax + by \\ cx + dy\end{pmatrix}$$
$$ \dbinom{x_{nuevo}}{y_{nuevo}} = \begin{pmatrix} 2 & 0 \\ 0 & 3\end{pmatrix} \dbinom{2}{1} = \dbinom{4}{3} $$

Así lo resolvemos en Python:

In [ ]:
from numpy import array

# Declaro los vectores i y j
i_hat = array([2, 0])
j_hat = array([0, 3])

# compongo la matriz base usando los vectores i y j
# y traspongo filas en columnas
basis = array([i_hat, j_hat]).transpose()

# declaro el vector v inicial
v = array([2,1])

# creo el nuevo vector
# transformando v con el producto punto
new_v = basis.dot(v)

print(new_v)

[4 3]


Ahora veamos gráficamente:
![image.png](attachment:image.png)

<div class="alert alert-block alert-warning">
<b>Ejercicio:</b> Tomemos el vector v = [2,1] y los vectores i y j transformados a [2,3] y [2,-1] respectivamente. ¿Qué pasa con v?
</div>

## Multiplicación de matrices

La multiplicación de matrices se puede entender como la aplicación de múltiples transformaciones sucesivas a un espacio vectorial. Cada matriz representa una transformación, y al multiplicar las matrices, combinamos estas transformaciones en una sola operación. Es como aplicar una serie de funciones a un vector, donde cada función representa una etapa de transformación.

Así aplicamos una rotación y luego un shear o sesgo/corte a un vector [x, y]

$$ \begin{pmatrix} 1 & 1 \\ 0 & 1\end{pmatrix} \begin{pmatrix} 0 & -1 \\ 1 & 0\end{pmatrix} \dbinom{x}{y}$$

En realidad, podemos consolidar estas dos transformaciones utilizando esta fórmula, aplicando una transformación sobre la última.

$$ \begin{pmatrix} a & b \\ c & d\end{pmatrix} \begin{pmatrix} e & f \\ g & h\end{pmatrix} = \begin{pmatrix} ae + bg & af + bh \\ ce + dy & cf + dh\end{pmatrix}$$

Para ejecutar esto en Python usando NumPy, puedes combinar las dos matrices simplemente usando el operador matmul() o @

In [ ]:
from numpy import array

# Transformacion 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# Transformacion 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# Combino Transformaciones
combined = transform2 @ transform1

# Test
print("COMBINED MATRIX:\n {}".format(combined))

# Aplico al vector v
v = array([1, 2])
print(combined.dot(v))

COMBINED MATRIX:
 [[ 1 -1]
 [ 1  0]]
[-1  1]



<div class="alert alert-block alert-danger">
<b>Importante:</b> ¡El orden en el que se aplica cada transformación importa! Los productos punto de matrices no son conmutativos.
</div>

Piensa en cada transformación como una función, y las aplicamos de la más interna a la más externa, al igual que las llamadas de funciones anidadas.

Veamos el ejemplo anterior pero aplicando las transformaciones en otro orden:

In [ ]:
from numpy import array

# Transformacion 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# Transformacion 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# Combino transformaciones, en otro orden
combined = transform1 @ transform2

# Test
print("COMBINED MATRIX:\n {}".format(combined))

# Aplico al vector v
v = array([1, 2])
print(combined.dot(v))

COMBINED MATRIX:
 [[ 0 -1]
 [ 1  1]]
[-2  3]


<div class="alert alert-block alert-info">
<b> Las transformaciones lineales y matrices son fundamentales en la ciencia de datos y el aprendizaje automático. Aunque rara vez visualizamos nuestros datos como espacios vectoriales y transformaciones lineales debido a la alta dimensionalidad, comprender la interpretación geométrica nos ayuda a entender el propósito y el efecto de las operaciones numéricas que realizamos. Esto nos permite aplicar conceptos de álgebra lineal de manera más efectiva en problemas de datos y aprendizaje automático.
</div>

## Determinantes


Cuando realizamos transformaciones lineales, a veces "expandimos" o "comprimimos" el espacio y el grado en que esto sucede puede ser útil.

![image.png](attachment:image.png)

El determinante describe cuánto cambia el tamaño de un área muestreada en un espacio vectorial debido a las transformaciones lineales. Es una medida de cuánto se "expande" o "comprime" el área bajo la transformación y proporciona información útil sobre el efecto global de la transformación en el espacio vectorial.

En la figura, el área aumenta 6 veces.

Calculemos el determinante en Python:

In [ ]:
from numpy.linalg import det
from numpy import array

i_hat = array([3, 0])
j_hat = array([0, 2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

6.0


Las deformaciones simples y las rotaciones no deberían afectar al determinante, ya que el área no cambia.
En la siguiente figura se observa que un corte simple no cambia el área.

![image.png](attachment:image.png)

Lo podemos comprobar numéricamente

In [ ]:
from numpy.linalg import det
from numpy import array

i_hat = array([1, 0])
j_hat = array([1, 1]) # Transformacion solo en vector j

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

1.0


Cuando escalamos una transformación, el determinante puede aumentar o disminuir, ya que esto afectará el área muestreada en el espacio vectorial. Si la orientación se invierte, es decir, si los vectores base intercambian posiciones en el sentido de las agujas del reloj, el determinante será negativo.

![image.png](attachment:image.png)

In [ ]:
# Un determinante negativo
from numpy.linalg import det
from numpy import array

i_hat = array([-2, 1])
j_hat = array([1, 2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

-5.000000000000001



Debido a que este determinante es negativo, rápidamente observamos que la orientación ha cambiado. Pero, de lejos, la información más crítica que te proporciona el determinante es si la transformación es linealmente dependiente. Si tienes un determinante igual a 0, eso significa que todo el espacio ha sido comprimido en una dimensión menor.

En la siguiente figura vemos dos transformaciones linealmente dependientes, donde un espacio 2D se comprime en una dimensión y un espacio 3D se comprime en dos dimensiones. El área y el volumen respectivamente en ambos casos son 0.

![image.png](attachment:image.png)

Comprobar si el determinante es igual a 0 es muy útil para detectar si una transformación tiene dependencia lineal. Cuando encuentres esto, es probable que te enfrentes a un problema difícil o incluso insoluble.

## Tipos de matrices especiales

### Matriz cuadrada
La matriz cuadrada es una matriz que tiene el mismo número de filas y columnas:

$$ \begin{pmatrix} 4 & 2 & 7 \\ 5 & 1 & 9 \\ 4 & 0 & 1\end{pmatrix} $$

Principalmente se utilizan para representar transformaciones lineales y son un requisito para muchas operaciones como la descomposición en auto valores.

### Matriz identidad
La matriz identidad es una matriz cuadrada que tiene una diagonal de 1 mientras que los otros valores son 0:

$$ \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{pmatrix} $$

La matriz identidad es especial porque representa la ausencia de cualquier transformación. Cuando la utilizamos en operaciones matriciales, actúa como el "estado inicial" o la base original antes de cualquier transformación. Esto es útil para deshacer transformaciones y resolver sistemas de ecuaciones.

### Matriz inversa
Una matriz inversa es aquella que revierte la transformación realizada por otra matriz.

Supongamos la matriz A:
$$ A = \begin{pmatrix} 4 & 2 & 4 \\ 5 & 3 & 7 \\ 9 & 3 & 6\end{pmatrix} $$

La inversa de la matriz es:

$$ A^{-1} = \begin{pmatrix} -1/2 & 0 & 1/3 \\ 11/2 & -2 & 4/3 \\ -2 & 1 & 1/3\end{pmatrix} $$

Cuando realizamos la multiplicación de matrices entre la inversa y A obtenemos una matriz identidad.

$$ A^{-1} A = \begin{pmatrix} -1/2 & 0 & 1/3 \\ 11/2 & -2 & 4/3 \\ -2 & 1 & 1/3\end{pmatrix} \begin{pmatrix} 4 & 2 & 4 \\ 5 & 3 & 7 \\ 9 & 3 & 6\end{pmatrix} = \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{pmatrix} $$

### Matriz diagonal
Similar a la matriz identidad está la matriz diagonal, que tiene una diagonal de valores no nulos mientras que el resto de los valores son 0. Las matrices diagonales son deseables en ciertos cálculos porque representan escalares simples aplicados a un espacio vectorial. Aparecen en algunas operaciones de álgebra lineal.

$$ \begin{pmatrix} 4 & 0 & 0 \\ 0 & 2 & 0 \\ 0 & 0 & 5\end{pmatrix} $$

### Matriz triangular
Similar a la matriz diagonal está la matriz triangular, que tiene una diagonal de valores no nulos frente a un triángulo de valores, mientras que el resto de los valores son 0.

$$ \begin{pmatrix} 4 & 2 & 9 \\ 0 & 1 & 6 \\ 0 & 0 & 5\end{pmatrix} $$

Las matrices triangulares son deseables en muchas tareas de análisis numérico, ya que suelen ser más fáciles de resolver en sistemas de ecuaciones.

### Matriz dispersa
Las matrices dispersas son aquellas en las que la mayoría de los elementos son cero. Desde el punto de vista computacional, son útiles porque no necesitan almacenar los ceros, lo que ahorra espacio de memoria y acelera los cálculos en operaciones matriciales.

$$ \begin{pmatrix} 0 & 0 & 0 \\ 0 & 0 & 2 \\ 0 & 0 & 0 \\ 0 & 0 & 0\end{pmatrix} $$

Cuando tienes matrices grandes y dispersas, es posible que uses explícitamente una función de dispersión para crear tu matriz.

## Sistemas de ecuaciones y la matriz inversa  

Uno de los casos de uso básicos para álgebra lineal es resolver sistemas de ecuaciones.  

Los sistemas de ecuaciones también sirven para aprender sobre matrices inversas.  

Supongamos que tenemos las siguientes ecuaciones y tenés que resolverlas para *x*, *y* y *z*:  

$$ 4x + 2y + 4z = 44 $$
$$ 5x + 3y + 7z = 44 $$
$$ 9x + 3y + 6z = 44 $$

Podemos probar a mano despejar las ecuaciones, y llegaríamos al resultado, pero si queremos dárselo a una compu para que lo resuelva, podríamos expresar este problema en notación matricial.  

Veamos cómo quedaría:  

$$ A = \left(\begin{matrix} 4 & 2 & 4 \\ 5 & 3 & 7 \\ 9 & 3 & 6\end{matrix}\right) $$  

$$ B = \left(\begin{matrix} 44 \\ 56 \\ 72 \end{matrix}\right) $$  

$$ X = \left(\begin{matrix} x \\ y \\ z \end{matrix}\right) $$  

Quedando el sistema de ecuaciones lineales: $$ AX = B $$  

O sea:  
$$ \left(\begin{matrix} 4 & 2 & 4 \\ 5 & 3 & 7 \\ 9 & 3 & 6\end{matrix}\right) . \left(\begin{matrix} x \\ y \\ z \end{matrix}\right) = \left(\begin{matrix} 44 \\ 56 \\ 72 \end{matrix}\right) $$

Y si es que este sistema de ecuaciones tiene solución, nosotros podríamos despejar *X* y obtener qué set de valores *x*, *y* y *z* satisfacen la igualdad.  
  
¿Cómo se despeja esto teniendo matrices?

---


$$ A X = B $$  
$$ A^{-1} A X = A^{-1} B $$  
$$ X = A^{-1} B $$  

Ahora tenemos que calcular la inversa de la matriz *A*, que como acá nos importa el concepto y no las cuentas (porque las vamos a hacer con *numpy*), quedaría:  

$$ A^{-1} = \left(\begin{matrix} -1/2 & 0 & 1/3 \\ 11/2 & -2 & 4/3 \\ -2 & 1 & 1/3 \end{matrix}\right) $$  

Pero siempre podemos corroborar que si la multiplicamos por *A*, vamos a obtener la matriz identidad:  

$$ A^{-1} A = \left(\begin{matrix} -1/2 & 0 & 1/3 \\ 11/2 & -2 & 4/3 \\ -2 & 1 & 1/3 \end{matrix}\right) \left(\begin{matrix} 4 & 2 & 4 \\ 5 & 3 & 7 \\ 9 & 3 & 6\end{matrix}\right) = \left(\begin{matrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{matrix}\right)$$  

Como *numpy* aproxima y no hace las cuentas exactas, para mostrar el ejemplo con *Python* y que nos dé exactamente la matriz identidad, vamos a usar el paquete *sympy*.

In [ ]:
from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

# El producto entre A y su inversa
# producen la matriz identidad
inverse = A.inv()
identity = inverse * A  # Ojo que esto no es numpy, es sympy, acá las matrices se multiplican con *

print("INVERSE: {}".format(inverse))
print("IDENTITY: {}".format(identity))

INVERSE: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
IDENTITY: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


Pero bueno, las aproximaciones de *numpy* no nos van a empeorar mucho las cuentas, y la realidad es que es la forma de hacerlo.  

La resolución del sistema de ecuaciones quedaría así:  

In [ ]:
from numpy import array
from numpy.linalg import inv

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = array([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = array([
    44,
    56,
    72
])

# Inversa de A por A debería darnos la matrix identidad:
print(inv(A) @ A)


[[ 1.00000000e+00 -2.22044605e-16 -4.44089210e-16]
 [ 2.66453526e-15  1.00000000e+00  1.77635684e-15]
 [-6.66133815e-16 -2.22044605e-16  1.00000000e+00]]


In [ ]:
# La resolución del sistema de ecuaciones:

X = inv(A).dot(B)

print('X =', X)

X = [ 2. 34. -8.]


Esto significa que:  
$$ A^{-1} B  = X $$  
$$ \left(\begin{matrix} -1/2 & 0 & 1/3 \\ 11/2 & -2 & 4/3 \\ -2 & 1 & 1/3 \end{matrix}\right) . \left(\begin{matrix} 44 \\ 56 \\ 72 \end{matrix}\right) = \left(\begin{matrix} x \\ y \\ z \end{matrix}\right)$$  
$$ \left(\begin{matrix} 2 \\ 34 \\ -8 \end{matrix}\right) = \left(\begin{matrix} x \\ y \\ z \end{matrix}\right) $$  

## Autovectores y autovalores

La *descomposición de matrices* consiste en descomponer una matriz en sus componentes básicos, de manera similar a como se factorizan los números (por ejemplo, 10 se puede descomponer en 2 × 5).

La descomposición de matrices es útil para tareas como encontrar matrices inversas y calcular determinantes, así como para la regresión lineal. Hay varios métodos de descomposición de matrices.

En este capítulo nos enfocaremos en un método común conocido como descomposición en autovalores, que se utiliza frecuentemente en el aprendizaje automático y el análisis de componentes principales. A este nivel, no profundizaremos en cada una de estas aplicaciones. Básicamente, la descomposición en autovalores nos ayuda a descomponer una matriz en partes más simples que son más útiles para diferentes tareas de aprendizaje automático. Es importante tener en cuenta que este método solo funciona con matrices cuadradas.

![image.png](attachment:image.png)

Si tenemos una matriz cuadrada A, tiene la siguiente ecuación de autovalores:

$$ A\nu = \lambda\nu $$

Veamos cómo se calculan los autovalores (eigenvalues) y autovectores (eigenvectors) en Python:

In [ ]:
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])

eigenvals, eigenvecs = eig(A)

print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)

EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


Entonces, ¿cómo reconstruimos la matriz A a partir de los autovectores y autovalores?

Recuerda la fórmula:
$$ A\nu = \lambda\nu $$

Para encontrar A debemos realizar
$$ A = Q \varLambda Q^{-1}$$

Donde Q representa a los autovectores, Λ son los autovalores en forma diagonal y luego tenemos la matriz inversa de Q.


Veamos el siguiente ejemplo en Python, comenzando por descomponer la matriz y luego recomponerla.

In [ ]:
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])

# Descompongo la matriz A
eigenvals, eigenvecs = eig(A)

print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)

# Recompongo la matriz A
print("\nREBUILD MATRIX")
Q = eigenvecs
R = inv(Q)

L = diag(eigenvals)
B = Q @ L @ R

print(B)

EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]

REBUILD MATRIX
[[1. 2.]
 [4. 5.]]


## Ejercicios

1. Relizar la transformación lineal de *v* = [1, 2] si *î* = [2, 0] y *j* = [0, 3/2]
2. Relizar la transformación lineal de *v* = [1, 2] si *î* = [-2, 1] y *j* = [1, -2]
3. Cuál es el determinante de la transformación si *î* = [1, 0] y *j* = [2, 2]
4. ¿Se pueden realizar dos o más transformaciones lineales en una sola transformación lineal? ¿Por qué sí o por qué no?
5. Resolver el siguiente sistema de ecuaciones
$$ 3x + y + 0z= 54 $$
$$ 2x + 4y + z = 12 $$
$$ 3x + y + 8z = 6 $$
6. ¿La siguiente matriz es linealmente dependiente? ¿Por qué sí o por qué no?
$$ \begin{pmatrix} 2 & 1 \\ 6 & 3 \end{pmatrix}  $$